# Generated by Django 2.0 on 2019-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=37, verbose_name='权限名')),
                ('url', models.CharField(max_length=37, verbose_name='链接')),
            ],
            options={
                'verbose_name_plural': '权限表',
                'verbose_name': '权限表',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=37, verbose_name='角色名称')),
                ('password', models.CharField(max_length=37, verbose_name='密码')),
                ('permission', models.ManyToManyField(to='rbac.Permission')),
            ],
            options={
                'verbose_name_plural': '角色表',
                'verbose_name': '角色表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=37, verbose_name='密码')),
                ('roles', models.ManyToManyField(to='rbac.Roles')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'verbose_name': '用户表',
            },
        ),
    ]
