# Generated by Django 2.0 on 2019-02-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='password',
        ),
    ]
