# Generated by Django 2.0.9 on 2019-03-01 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_remove_roles_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限组名')),
            ],
            options={
                'verbose_name_plural': '权限组',
                'verbose_name': '权限组',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.IntegerField(choices=[(1, 'add'), (2, 'delete'), (3, 'update'), (4, 'select')], default=4, verbose_name='动作'),
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='rbac.PermissionGroup'),
        ),
    ]
